version: 2
project_name: "sensu-check-memory"
builds:
  - main: ./cmd/check-memory/main.go
    id: "check-memory"
    env:
    - CGO_ENABLED=0
    ldflags: '-s -w -X github.com/sensu-community/sensu-plugin-sdk/version.version={{.Version}} -X github.com/sensu-community/sensu-plugin-sdk/version.commit={{.Commit}} -X github.com/sensu-community/sensu-plugin-sdk/version.date={{.Date}}'
    binary: bin/check-memory
    targets:
      - darwin_amd64
      - linux_386
      - linux_amd64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64
      - windows_386
      - windows_amd64

  - main: ./cmd/check-swap/main.go
    id: "check-swap"
    env:
    - CGO_ENABLED=0
    ldflags: '-s -w -X github.com/sensu-community/sensu-plugin-sdk/version.version={{.Version}} -X github.com/sensu-community/sensu-plugin-sdk/version.commit={{.Commit}} -X github.com/sensu-community/sensu-plugin-sdk/version.date={{.Date}}'
    binary: bin/check-swap
    targets:
      - darwin_amd64
      - linux_386
      - linux_amd64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64
      - windows_386
      - windows_amd64

  - main: ./cmd/metrics-memory/main.go
    id: "metrics-memory"
    env:
    - CGO_ENABLED=0
    ldflags: '-s -w -X github.com/sensu-community/sensu-plugin-sdk/version.version={{.Version}} -X github.com/sensu-community/sensu-plugin-sdk/version.commit={{.Commit}} -X github.com/sensu-community/sensu-plugin-sdk/version.date={{.Date}}'
    binary: bin/metrics-memory
    targets:
      - darwin_amd64
      - linux_386
      - linux_amd64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64
      - windows_386
      - windows_amd64

  - main: ./cmd/metrics-memory-vmstat/main.go
    id: "metrics-memory-vmstat"
    env:
    - CGO_ENABLED=0
    ldflags: '-s -w -X github.com/sensu-community/sensu-plugin-sdk/version.version={{.Version}} -X github.com/sensu-community/sensu-plugin-sdk/version.commit={{.Commit}} -X github.com/sensu-community/sensu-plugin-sdk/version.date={{.Date}}'
    binary: bin/metrics-memory-vmstat
    targets:
      - linux_386
      - linux_amd64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    ids:
      - check-memory
      - check-swap
      - metrics-memory
    formats: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

  - id: tar-linux
    ids:
      - metrics-memory-vmstat
    formats: tar.gz
    name_template: "{{ .ProjectName }}-vmstat_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
